spring:
  application:
    name: backoffice
  config:
    import:
#      - classpath:milter-properties.yml
#      - classpath:properties/kafka.yml
      - classpath:openjpa.yml
  codec:
    max-in-memory-size: 30MB
